
language: node_js

node_js:
  - 10
  - 8

install:
  - npm install
  - npm install -g codecov coveralls

script:
  - npm run lint
  - npm run test
  - codecov
  - cat ./coverage/lcov.info | coveralls

sudo: false
